In [3]:
################# Final : Approche Supervisé Encodage - One -Hot aussi de la question pas seulement des propositions et du label ########################

import random
import numpy as np
import tensorflow as tf
import json

with open("data.json", "r") as json_file:
    data = json.load(json_file)["questions"]

def preprocess_data(data):
    processed_data = []
    vocab = set()  # Créer un ensemble pour stocker toutes les lettres ou mots uniques
    
    # Parcourir les données pour construire le vocabulaire
    for question_data in data:
        question = question_data["question"]
        options = question_data["options"]
        answer = question_data["answer"]
        vocab.update(question)  # Ajouter toutes les lettres ou mots de la question au vocabulaire
        for option in options:
            vocab.update(option)  # Ajouter toutes les lettres ou mots des options au vocabulaire
    
    # Convertir le vocabulaire en une liste triée
    vocab = sorted(vocab)
    
    # Créer un dictionnaire pour mapper chaque caractère ou mot à un index
    vocab_mapping = {char: idx for idx, char in enumerate(vocab)}
    
    # Encoder les données
    for question_data in data:
        question = question_data["question"]
        options = question_data["options"]
        answer = question_data["answer"]
        
        # Encoder la question avec one-hot encoding
        question_one_hot = [vocab_mapping[char] for char in question]
        # print(question_one_hot)

        question_one_hot = tf.keras.utils.to_categorical(question_one_hot, num_classes=len(vocab))
        # print(question_one_hot)

        # Padding des options pour avoir la même longueur
        max_option_length = max(len(option) for option in options)
        padded_options = [[vocab_mapping[char] for char in option] + [0] * (max_option_length - len(option)) for option in options]
        options_one_hot = np.array(padded_options)  # Convertir en tableau NumPy
        
        print(options_one_hot)

        # Encoder la réponse avec one-hot encoding
        answer_index = options.index(answer)
        answer_one_hot = tf.keras.utils.to_categorical(answer_index, num_classes=len(options))
        
        processed_data.append((question_one_hot, options_one_hot, answer_one_hot))
    
    return processed_data, vocab_mapping

processed_data, vocab_mapping = preprocess_data(data)


[[40 65 56  0 63 48 65  0 56 61 66 52 65 67 56 62 61]
 [40 65 56  0 53 68 66 56 62 61  0  0  0  0  0  0  0]
 [40 65 56  0 65 48 63 56 51 52  0  0  0  0  0  0  0]
 [40 65 56  0 80 72  0 49 68 59 59 52 66  0  0  0  0]]
[[35  2 61  0 59 62 54  0 61  3]
 [35  2 61 46 11  3  0  0  0  0]
 [35  2 61  3  0  0  0  0  0  0]
 [35  2 59 62 54  0 61  3  0  0]]
[[38 52 50 55 52 65 50 55 52  0 66 80 75 64 68 52 61 67 56 52 59 59 52]
 [38 52 50 55 52 65 50 55 52  0 49 56 61 48 56 65 52  0  0  0  0  0  0]
 [38 52 50 55 52 65 50 55 52  0 52 70 63 62 61 52 61 67 56 52 59 59 52]
 [38 52 50 55 52 65 50 55 52  0 59 56 61 80 75 48 56 65 52  0  0  0  0]]
[[35  2 59 62 54  0 61  3  0  0]
 [35  2 61  3  0  0  0  0  0  0]
 [35  2 61  0 59 62 54  0 61  3]
 [35  2 61 46 11  3  0  0  0  0]]
[[40 65 56  0 63 48 65  0 56 61 66 52 65 67 56 62 61]
 [40 65 56  0 53 68 66 56 62 61  0  0  0  0  0  0  0]
 [40 65 56  0 65 48 63 56 51 52  0  0  0  0  0  0  0]
 [40 65 56  0 80 72  0 49 68 59 59 52 66  0  0  0  0]]
[[40 65 56 

In [6]:
#  print(processed_data)
print(vocab_mapping)


{' ': 0, "'": 1, '(': 2, ')': 3, '+': 4, ',': 5, '-': 6, '.': 7, '/': 8, '0': 9, '1': 10, '2': 11, '3': 12, '4': 13, '5': 14, '6': 15, '7': 16, '8': 17, '9': 18, ':': 19, '<': 20, '>': 21, '?': 22, 'A': 23, 'B': 24, 'C': 25, 'D': 26, 'E': 27, 'F': 28, 'H': 29, 'I': 30, 'J': 31, 'K': 32, 'L': 33, 'N': 34, 'O': 35, 'P': 36, 'Q': 37, 'R': 38, 'S': 39, 'T': 40, 'U': 41, 'V': 42, 'W': 43, 'X': 44, 'Y': 45, '^': 46, '_': 47, 'a': 48, 'b': 49, 'c': 50, 'd': 51, 'e': 52, 'f': 53, 'g': 54, 'h': 55, 'i': 56, 'j': 57, 'k': 58, 'l': 59, 'm': 60, 'n': 61, 'o': 62, 'p': 63, 'q': 64, 'r': 65, 's': 66, 't': 67, 'u': 68, 'v': 69, 'x': 70, 'y': 71, '\xa0': 72, '¢': 73, '¨': 74, '©': 75, 'ª': 76, '®': 77, '²': 78, 'Â': 79, 'Ã': 80}


In [7]:
print(processed_data[0][1])

[[40 65 56  0 63 48 65  0 56 61 66 52 65 67 56 62 61]
 [40 65 56  0 53 68 66 56 62 61  0  0  0  0  0  0  0]
 [40 65 56  0 65 48 63 56 51 52  0  0  0  0  0  0  0]
 [40 65 56  0 80 72  0 49 68 59 59 52 66  0  0  0  0]]
